numero01 = int(input('Digite um número: '))
numero02 = int(input('Digite outro número: '))
numero03 = int(input('Digite outro número: '))
numero04 = int(input('Digite outro número: '))
numero05 = int(input('Digite mais um número: '))
print(f'O maior número lido foi {max(numero01, numero02, numero03, numero04, numero05)}')
print(f'O menor número lido foi {min(numero01, numero02, numero03, numero04, numero05)}')
print(f'A média aritimética dos núemros é {(numero01+numero02+numero03+numero04+numero05) / 5}')
